### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Zendrex** [LuxusDarkangel/Bungeecord-KFix#1]
would it be possible for you to update this patch to work with a later variant of bungee?

https://github.com/HexagonMC/BungeeCord

**Comment by LuxusDarkangel** [comment]
I will take a look at it later, no promises though, I'm out of free time lately.

**Comment by LuxusDarkangel** [comment]
Okay, i was going to do it, but you have a forked repository including those patches already. I am missing something?

**Comment by Zendrex** [comment]
Ive started attempting it however im no developer and im sure my variant will fail.
 Im a guy who knows linux and how to manage hardware, not develop plugins and mods. :P

I was just giving it a shot, nothing more. :|

**Comment by LuxusDarkangel** [comment]
It's not a part used by plugins, just how packets are handled so if it compiles and starts without errors it's okay, it won't affect any plugin. If not, then i'll try to implement it myself.

**Comment by Zendrex** [comment]
Can you check over my changes and see if it is correct?

**Comment by Zendrex** [comment]
And when I was saying im not a developer of plugins and mods, etc. I was covering the entire genre of development side of minecraft/bungee/etc. I have very low expectations for myself to develop minecraft related things. I make shell scripts, run linux machines, not develop.

**Comment by Zendrex** [comment]
Im giving my attempt a try will return with results.

**Comment by Zendrex** [comment]
Yea im getting compiling errors. :/

**Comment by LuxusDarkangel** [comment]
Okay, i'll make it then.

**Comment by LuxusDarkangel** [comment]
It's ready. If you want the source code you can find it in the 1.9 branch, and [here](https://mega.nz/#!hF0TjLwK!pynvpqd_DTg7u_7tjkpgGGQyMmzZw0HM5Hk8Hnn4p00) the precompiled jar.

**Comment by Zendrex** [comment]
Would the patches by Yive be needed as well?

https://github.com/TCPR/BungeeCord/commits?author=Yive

**Comment by LuxusDarkangel** [comment]
Click on the "[...](http://i.imgur.com/KO0yvaM.png)"

**Comment by Zendrex** [comment]
Sorry, was tired. Works like a charm! Thanks for doing this, you are a life saver. :)
